# Generated by Django 4.1.4 on 2022-12-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0003_port_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(name="port", options={"ordering": ["-id"]},),
        migrations.AlterField(
            model_name="port",
            name="photo",
            field=models.ImageField(blank=True, upload_to="instagram/port/%Y%m%d"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "port_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="instagram.port"
                    ),
                ),
            ],
        ),
    ]
