# Generated by Django 4.1.4 on 2022-12-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0008_port_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="port_key",
            field=models.ForeignKey(
                limit_choices_to={"is_public": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="instagram.port",
            ),
        ),
    ]
